# Generated by Django 4.0.3 on 2022-03-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_genset', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sparepart', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.CharField(max_length=10)),
                ('alasan', models.TextField()),
                ('pic', models.CharField(max_length=255)),
                ('genset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genset')),
            ],
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_servis', models.CharField(max_length=200)),
                ('pic', models.CharField(max_length=255)),
                ('genset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genset')),
                ('sparepart', models.ManyToManyField(to='app.sparepart')),
            ],
        ),
        migrations.AddField(
            model_name='genset',
            name='sparepart',
            field=models.ManyToManyField(to='app.sparepart'),
        ),
    ]
