# Generated by Django 4.0.3 on 2022-03-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genset',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
