# Generated by Django 4.0.3 on 2022-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='tanggal_servis',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilitas',
            name='tanggal_pakai',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
