# Generated by Django 4.0.3 on 2022-03-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_genset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineGenset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merek', models.CharField(max_length=255, null=True)),
                ('tipe', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merek', models.CharField(max_length=255, null=True)),
                ('sn', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merek', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipeGenset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='genset',
            name='nama_genset',
        ),
        migrations.AddField(
            model_name='genset',
            name='kva',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genset',
            name='mpu',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genset',
            name='nopol',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genset',
            name='sn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genset',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servis',
            name='pic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='nama_sparepart',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilitas',
            name='alasan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='utilitas',
            name='pic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genset',
            name='merek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.merek'),
        ),
        migrations.AddField(
            model_name='genset',
            name='tipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipegenset'),
        ),
    ]
