# Generated by Django 4.0.3 on 2022-03-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_enginegenset_generator_merek_tipegenset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='nama_sparepart',
            new_name='jenis_sparepart',
        ),
        migrations.RemoveField(
            model_name='genset',
            name='sparepart',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='merek',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='pn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='KebutuhanSparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.CharField(max_length=255, null=True)),
                ('sparepart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sparepart')),
            ],
        ),
        migrations.AlterField(
            model_name='servis',
            name='sparepart',
            field=models.ManyToManyField(to='app.kebutuhansparepart'),
        ),
    ]
