# Generated by Django 4.0.3 on 2022-04-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagenset',
            name='jenis_genset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
