# Generated by Django 4.0.3 on 2022-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_datagenset_status_alter_datagenset_sparepart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datagenset',
            name='status',
        ),
        migrations.AddField(
            model_name='gensetutility',
            name='tanggal_pemakaian',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepartutility',
            name='tanggal_servis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datagenset',
            name='status_genset',
            field=models.CharField(blank=True, choices=[('READY', 'READY'), ('SERVIS', 'SERVIS'), ('DIPAKAI', 'SERVIS'), ('GROUNDED', 'GROUNDED')], max_length=255, null=True),
        ),
    ]
