# Generated by Django 4.0.3 on 2022-04-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sparepartutility_jenis_servis'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagenset',
            name='jumlah_servis',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sparepartutility',
            name='jenis_servis',
            field=models.CharField(blank=True, choices=[('250 JAM', '250 JAM'), ('2500 JAM', '2500 JAM'), ('10000 JAM', '10000 JAM')], max_length=255, null=True),
        ),
    ]
