# Generated by Django 4.0.3 on 2022-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_datagenset_jumlah_servis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipesparepart',
            name='limit_notif',
            field=models.IntegerField(default=0),
        ),
    ]
